### ISSUE TITLE
vibration motor for 107HR plus

### ISSUE THREAD

**Issue by scientistnobee** [micooke/arduino-nRF5-smartwatches#12]
Hi Mike,

Do you have any guess on what might be a pin for the vibration motor for 107Hr plus?

**Comment by micooke** [comment]
No I don't,and I don't have one im sorry.
If you load https://github.com/micooke/arduino-nRF5-smartwatches/blob/master/libraries/examples/Examples/ReverseEngineerSmartwatchPins/ReverseEngineerSmartwatchPins.ino then you can trigger each digital pin individually using the uart command interface, so try that!

**Comment by micooke** [comment]
It should be visible in the IDE under examples

**Comment by scientistnobee** [comment]
Thanks, Mark. I will see this.

**Comment by scientistnobee** [comment]
Hi Mark, I found 25 as Vibration motor pin.

**Comment by micooke** [comment]
Thanks! I will update this when I get time (I'm a bit slow at the moment with updates)

**Comment by micooke** [comment]
Done!

**Comment by scientistnobee** [comment]
I hope you can update the table as well
