### ISSUE TITLE
ID115/115HR

### ISSUE THREAD

**Issue by gitkobold** [micooke/arduino-nRF5-smartwatches#3]
Hi!
New variants are in stores. It would be nice from you if you could check that.
Thanks a lot

**Comment by micooke** [comment]
Hi @gitkobold. I have only bought smartwatches that can be opened non-destructively, and unfortunately the 115 isn't one of them. 
If you have one and can provide the pin mapping im happy to create a variant, otherwise im happy to accept PRs. 
Cheers
