### ISSUE TITLE
Regarding T28 fitness sensor

### ISSUE THREAD

**Issue by scientistnobee** [micooke/arduino-nRF5-smartwatches#8]
Hi Mark, 

I would like to buy T28 fitness tracker just for the GPS sensor and Temparature sensor. Are you able to get any info from these sensors? Any recommendations on where to buy these fitness sensors from Europe?

**Comment by micooke** [comment]
Sorry for the delay. I bought mine from aliexpress. I believe gearbest also sell them. Lemdoie is just one of the brands, i searched for gps smartwatch from memory.
The gps is a simple serial ublox device, so a library like tinygps will work. The pinout is in the t28 variant.h. Check out my last commit, I'm pretty sure one of my changes was in the comment on those pins.
I'm pretty sure the temperature is on the nrf52. Should be easy to find (look at sandeeps repo), but i wouldn't trust it. I have two watches that have temperature, neither was cheap and they are both very inaccurate

**Comment by scientistnobee** [comment]
Thanks for the info. I think you mentioned that there is a separate temperature sensor HP203B. Hope it works. I will order this one.

**Comment by micooke** [comment]
Ah yes, i forgot about that. Just a heads up that the software i2c library is a little broken. Its not throttled and doesn't work with some devices. The hp203b will still work hardware i2c (need to modify variant.h pins), I just can't remember if it works for the software i2c.
I was planning to look at stm32duino repo as that has a software i2c library that should work

**Comment by scientistnobee** [comment]
Okay, great. I will test my luck.

**Comment by micooke** [comment]
It looks like the t28 is getting harder to get. @curtpw - can you recommend a watch with gps and temp sensor? I noticed you have rev engineered a lot of the new colour screen watches.

**Comment by micooke** [comment]
I found a t28 https://s.click.aliexpress.com/e/bBTPQ1nL
I searched aliexpress for "gps nordic"

This one might be worth trying?
F18 - https://s.click.aliexpress.com/e/bXxxKRqp
Colour round oled, nrf52832, optical hr and apparently has gps. The back cover unscrews too
