### ISSUE TITLE
adding DS-D6 bracelet

### ISSUE THREAD

**Issue by fanoush** [micooke/arduino-nRF5-smartwatches#9]
Hi I am currently playing with DS-D6 bracelet see https://github.com/fanoush/ds-d6
Perhaps you can add it to your project? Currently I have no time to do pull requests (possibly later?) but you can add it if you wish.

It is nRF52832 based bracelet sold at gearbest.com for couple of months already. Now it is even on sale for $8 :-)

So far I have backed up firmware via SWD, figured out some GPIOs (serial, i2c, spi) and have Espruino running on the watch. The serial console is on USB charging connector data pins and SWD is right below screen glass so it is very easy to hack, no need to take it apart completely thanks to FCC photos! Also the body is hidden in the wristband so the glass can be put back with no visible damage :-)

Currently I am figuring out display and then  DFU over serial as the bootloader has serial port opened on usb data pins when it is in DFU mode!

Pin mapping is here https://github.com/fanoush/ds-d6/wiki/Hardware

**Comment by micooke** [comment]
Great work! Happy to add it, but I'm short on time at the moment. Good work with the firmware dump, I never got that to work for mine :)

**Comment by micooke** [comment]
I should be adding this in the next day or so. Cheers

**Comment by fanoush** [comment]
just FYI - working DFU update was also tested by [najnesnaj](https://gitter.im/nRF51822-Arduino-Mbed-smart-watch/Lobby?at=5c40b3e8746d4a677aca7c17) and his code is here https://github.com/najnesnaj/platformio-ds6

As Espruino is working beautifully for me I don't have a need for Arduino environment myself but the more ways there are the better of course :-)

**Comment by micooke** [comment]
Couldn't agree more! The Arduino core uses a pretty old SDK, but its what i know.
Thanks for this, ive added the DS-D6 to my release today (I got more done than i expected last night)
Cheers

**Comment by fanoush** [comment]
Great, thanks. Did you actually get DS-D6 yourself? It is cheap but still I guess one cannot get all of them. I just wonder whether it was tested with real device.

**Comment by micooke** [comment]
No, I haven't. I actually have three of the variants, and I'm not really doing anything with them
